[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aws-durable-execution-sdk-python"
version = "0.0.0"

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]
